Film_Review/urls.py
from django.urls import path
from Film_Review import views

app_name = 'ReviewFlix'

urlpatterns = [
    path('', views.home, name='Home'),
    path('faq/', views.faq, name='FAQ'),
    path('register/', views.register, name='Register'),
    path('watchlist/', views.watchlist, name='Watchlist'),
    path('add_to_watchlist/', views.add_to_watchlist, name='add_to_watchlist'),
    path('remove_from_watchlist/', views.remove_from_watchlist, name='remove_from_watchlist'),
    path('check_watchlist/', views.check_watchlist, name='check_watchlist'),
    path('addAMovie/', views.addAMovie, name='AddAMovie'),
    path('genres/', views.genres, name='Genres'),
    path('thriller/', views.thriller, name='Thriller'),
    path('animated/', views.animated, name='Animated'),
    path('comedy/', views.comedy, name='Comedy'),
    path('horror/', views.horror, name='Horror'),
    path('drama/', views.drama, name='Drama'),
    path('documentary/', views.documentary, name='Documentary'),
    path('login/', views.user_login, name='Login'),
    path('logout/', views.user_logout, name='Logout'),
    path('film/<int:film_id>/', views.individual_film, name='Film'),
    path('film/<int:film_id>/review/', views.review_for_film, name='FilmReview'),
    path('like_review/', views.like_review, name='like_review'),
]

Film_Reviews_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from Film_Review import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.home, name = 'Home'),
    path('ReviewFlix/', include('Film_Review.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/ReviewFlix/Animated.html
{% extends 'ReviewFlix/base.html' %}
{% load staticfiles %}


{% block title_block %}
    Animated
{% endblock %}

{% block additional_css %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/css/splide.min.css" rel="stylesheet">
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/js/splide.min.js"></script>
    <script src="{% static 'js/carousel.js' %}"></script>
{% endblock %}

{% block body_block %}
    <h1 style="text-align: center;" >Welcome to the Animated Movies Page</h1>
    <section id="image-carousel" class="splide" aria-label="Beautiful Images">
        <div class="splide__track">
                <ul class="splide__list">
                {% for film in films %}
                    <li class="splide__slide">
                        <div class="title_button">
                            <h2 class="movie_title">{{ film.Title }}</h2>
                            <a href="{% url 'ReviewFlix:Film' film.id %}" class="button">More Details</a>
                        </div>
                        {% if film.image %}
                            <img class="img_slide_bg" src="{{ film.image.url }}" alt="{{ film.Title }}"/>
                        {% else %}
                            <p>No image available.</p>
                        {% endif %}
                        
                    </li>

                {% endfor %}  
                </ul>

               
        </div>
    </section>
{% endblock %}

templates/ReviewFlix/Comedy.html
{% extends 'ReviewFlix/base.html' %}
{% load staticfiles %}


{% block title_block %}
    Comedy
{% endblock %}

{% block additional_css %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/css/splide.min.css" rel="stylesheet">
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/js/splide.min.js"></script>
    <script src="{% static 'js/carousel.js' %}"></script>
{% endblock %}

{% block body_block %}
    <h1 style="text-align: center;">Welcome to the Comedy Movies Page</h1>
    <section id="image-carousel" class="splide" aria-label="Beautiful Images">
        <div class="splide__track">
                <ul class="splide__list">
                {% for film in films %}
                    <li class="splide__slide">
                        <div class="title_button">
                            <h2 class="movie_title">{{ film.Title }}</h2>
                            <a href="{% url 'ReviewFlix:Film' film.id %}" class="button">More Details</a>
                        </div>
                        {% if film.image %}
                            <img class="img_slide_bg" src="{{ film.image.url }}" alt="{{ film.Title }}"/>
                        {% else %}
                            <p>No image available.</p>
                        {% endif %}
                        
                    </li>

                {% endfor %}  
                </ul>

               
        </div>
    </section>
{% endblock %}

templates/ReviewFlix/Documentary.html
{% extends 'ReviewFlix/base.html' %}
{% load staticfiles %}


{% block title_block %}
    Documentary
{% endblock %}

{% block additional_css %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/css/splide.min.css" rel="stylesheet">
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/js/splide.min.js"></script>
    <script src="{% static 'js/carousel.js' %}"></script>
{% endblock %}

{% block body_block %}
    <h1 style="text-align: center;">Welcome to the Documentary Movies Page</h1>
    <section id="image-carousel" class="splide" aria-label="Beautiful Images">
        <div class="splide__track">
                <ul class="splide__list">
                {% for film in films %}
                    <li class="splide__slide">
                        <div class="title_button">
                            <h2 class="movie_title">{{ film.Title }}</h2>
                            <a href="{% url 'ReviewFlix:Film' film.id %}" class="button">More Details</a>
                        </div>
                        {% if film.image %}
                            <img class="img_slide_bg" src="{{ film.image.url }}" alt="{{ film.Title }}"/>
                        {% else %}
                            <p>No image available.</p>
                        {% endif %}
                        
                    </li>

                {% endfor %}  
                </ul>

               
        </div>
    </section>
{% endblock %}

templates/ReviewFlix/Drama.html
{% extends 'ReviewFlix/base.html' %}
{% load staticfiles %}


{% block title_block %}
    Drama
{% endblock %}

{% block additional_css %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/css/splide.min.css" rel="stylesheet">
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/js/splide.min.js"></script>
    <script src="{% static 'js/carousel.js' %}"></script>
{% endblock %}

{% block body_block %}
    <h1 style="text-align: center;">Welcome to the Drama Movies Page</h1>
    <section id="image-carousel" class="splide" aria-label="Beautiful Images">
        <div class="splide__track">
                <ul class="splide__list">
                {% for film in films %}
                    <li class="splide__slide">
                        <div class="title_button">
                            <h2 class="movie_title">{{ film.Title }}</h2>
                            <a href="{% url 'ReviewFlix:Film' film.id %}" class="button">More Details</a>
                        </div>
                        {% if film.image %}
                            <img class="img_slide_bg" src="{{ film.image.url }}" alt="{{ film.Title }}"/>
                        {% else %}
                            <p>No image available.</p>
                        {% endif %}
                        
                    </li>

                {% endfor %}  
                </ul>

               
        </div>
    </section>
{% endblock %}

templates/ReviewFlix/Film.html
{% extends 'ReviewFlix/base.html' %}

{% load staticfiles %}


{% block title_block %}
    {{ film.Title }}
{% endblock %}

{% block additional_css %}
    <link rel="stylesheet" href="{% static 'css/film.css' %}">

{% endblock %}

{% block body_block %}
    <div class="film-details-container">
        <div class="film_details">
            <div class="wrapper">
                {% if film.image %}
                    <div class="film_image">
                        <img src="{{ film.image.url }}" alt="{{ film.Title }} Image" class="film_img">
                    </div>
                {% endif %}

                <div class="information">
                    <h1>{{ film.Title }}</h1>
                    <div class="text_wrapper">
                        <p><strong>Genre:</strong> {{ film.Genre }}</p>
                        <p><strong>Description:</strong> {{ film.Description }}</p>
                        <p><strong>Release Date:</strong> {{ film.ReleaseDate }}</p>
                        <p><strong>Director:</strong> {{ film.Director }}</p>
                        <p><strong>Cast:</strong> {{ film.Cast }}</p>
                        {% if reviews %}
                            <p><strong>Average Rating:</strong> {{ average_rating|floatformat:1 }}</p>
                        {% endif %}
                    </div>
                    
                    <div class="btn_wrapper">
                        <a class="btn" href="{% url 'ReviewFlix:FilmReview' film_id=film.id %}">Write a Review</a>
                        {% if user.is_authenticated %}
                        <form id="watchlist-form" method="post" action="{% url 'ReviewFlix:add_to_watchlist' %}">
                            {% csrf_token %}
                            <input class="btn input_btn" type="hidden" name="film_id" value="{{ film.id }}">
                            <input class="btn input_btn" type="submit" value="Add to Watchlist" id="watchlist-btn">
                        </form>
                        {% endif %}
                    </div>
                </div> 
            </div>
        </div>
    </div>

    <div class="review-container">
        <h2>Reviews:</h2>

        {% if reviews %}
            <div>
                <form method="GET" action="">
                  <label for="sort">Sort By:</label>
                  <select name="sort">
                    <option value="-DatePublished">Most Recently Added</option>
                    <option value="Rating">Rating (Low to High)</option>
                    <option value="-Rating">Rating (High to Low)</option>
                    <option value="-likes">Likes (Most to Least)</option>
                    <option value="likes">Likes (Least to Most)</option>
                  </select>
                  <button class ="btn" type="submit">Sort</button>
                </form>
              </div>
            <ul>
                {% for review in reviews %}
                    <div class="review">
                        <p class="review-author">Author: {{ review.Username }}</p>
                        <p class="review-rating">Rating: {{ review.Rating }}</p>
                        <p class="review-description">Description: {{ review.Description }}</p>
                        <p class="review-likes">Likes: <span id="likes-count-{{ review.id }}">{{ review.likes }}</span></p>
                        <p class="review-date">Published on: {{ review.DatePublished }}</p>
                        <button class="btn like-btn" data-review-id="{{ review.id }}">Like</button>
                    </div>
                {% endfor %}
            </ul>
        {% else %}
            <p class="no-reviews">No reviews available for this film.</p>
        {% endif %}
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function() {
            // Loop through each like button
            $(".like-btn").each(function () {
                 // Get the review ID associated with the like button
                var reviewId = $(this).data("review-id");
                var likeButton = $(this);
                // AJAX request to check if the user has already liked the review
                $.ajax({
                    url: "{% url 'ReviewFlix:check_like_status' %}", // URL to the check_like_status view
                    type: "GET", // HTTP method type
                    data: { // Data to send in the request
                        review_id: reviewId,
                    },
                    dataType: "json", // Expected response data type
                    success: function (response) {  // Function to execute on successful response
                        if (response.status === "success") { // If the response indicates success
                            // Update the like button text based on whether the user has liked the review
                            if (response.liked) {
                                likeButton.text("Unlike");
                            } else {
                                likeButton.text("Like");
                            }
                        } else {
                            console.error(response.message);
                        }
                    },
                    error: function (xhr, status, error) {
                        console.error(xhr.responseText);
                    }
                });
            });
            // Event listener for clicking the like button
            $(".like-btn").click(function () {
                // Get the review ID associated with the clicked like button
                var reviewId = $(this).data("review-id");
                var likeButton = $(this);

                $.ajax({
                    url: "{% url 'ReviewFlix:like_review' %}", // URL to the like_review view
                    type: "POST", // HTTP method type
                    data: { // Data to send in the request
                        review_id: reviewId,
                        csrfmiddlewaretoken: "{{ csrf_token }}"
                    },
                    dataType: "json", // Expected response data type
                    success: function (response) { // Function to execute on successful response
                        if (response.status === "success") { // If the response indicates success
                            var newLikes = response.new_likes; // New number of likes
                            $("#likes-count-" + reviewId).text(newLikes); // Update the likes count in the HTML
                            // Toggle between "Like" and "Unlike" based on the current button text
                            if (likeButton.text() === "Like") {
                                likeButton.text("Unlike");
                            } else {
                                likeButton.text("Like");
                            }
                        } else {
                            alert(response.message);
                        }
                    },
                    error: function (xhr, status, error) {
                        console.error(xhr.responseText);
                    }
                });
            });

             // Get the film ID
            var filmId = "{{ film.id }}";
            // AJAX request to check if the film is in the user's watchlist
            $.ajax({
                type: "GET", // HTTP method type
                url: "/ReviewFlix/check_watchlist/", // URL to the check_watchlist view
                data: { film_id: filmId }, // Data to send in the request (film ID)
                success: function(response) { // Function to execute on successful response
                    if (response.in_watchlist) { // If the film is in the user's watchlist
                        $("#watchlist-btn").val("Remove from Watchlist"); // Update the watchlist button text
                        $("#watchlist-form").attr("action", "{% url 'ReviewFlix:remove_from_watchlist' %}"); // Update the form action
                    } else { // If the film is not in the user's watchlist
                        $("#watchlist-btn").val("Add to Watchlist"); // Update the watchlist button text
                        $("#watchlist-form").attr("action", "{% url 'ReviewFlix:add_to_watchlist' %}"); // Update the form action
                    }
                }
            });

            // Event listener for clicking the watchlist button
            $("#watchlist-btn").click(function(e) {
                e.preventDefault(); // Prevent the default form submission
                var form = $(this).closest("form"); // Get the closest form element
                var action = form.attr("action"); // Get the form action
                // AJAX request to add/remove a film from the user's watchlist
                $.ajax({
                    type: "POST", // HTTP method type
                    url: action, // URL to the add_to_watchlist or remove_from_watchlist view
                    data: form.serialize(), // Data to send in the request 
                    success: function(response) { // Function to execute on successful response
                         // Toggle between "Add to Watchlist" and "Remove from Watchlist" based on button text
                        if ($("#watchlist-btn").val() === "Remove from Watchlist") {
                            $("#watchlist-btn").val("Add to Watchlist"); // Update button text
                            $("#watchlist-form").attr("action", "{% url 'ReviewFlix:add_to_watchlist' %}"); // Update form action
                        } else {
                            $("#watchlist-btn").val("Remove from Watchlist"); // Update button text
                            $("#watchlist-form").attr("action", "{% url 'ReviewFlix:remove_from_watchlist' %}"); // Update form action
                        }
                    }
                });
            });
        });
    </script>
{% endblock %}

templates/ReviewFlix/Genres.html
{% extends 'ReviewFlix/base.html' %}
{% load static %}

{% block title_block %}
    Genres
{% endblock %}

{% block additional_css %}
    <link rel="stylesheet" href="{% static 'css/genre.css' %}">
{% endblock %}

{% block body_block %}
    <div class="genres-container">
        <h1>Welcome to the Genres Page</h1>
        <p>Here you can find a list of all the genres available on ReviewFlix</p>
        <div class="genres">
            <div class="genre">
                <img src="{% static 'film_images/drama.jpg' %}" alt="Drama">
                <h3><a href="{% url 'ReviewFlix:Drama'%}">Drama</a></h3>
            </div>
            <div class="genre">
                <img src="{% static 'film_images/comedy.jpg' %}" alt="Comedy">
                <h3><a href="{% url 'ReviewFlix:Comedy'%}">Comedy</a></h3>
            </div>
            <div class="genre">
                <img src="{% static 'film_images/horror.jpg' %}" alt="Horror">
                <h3><a href="{% url 'ReviewFlix:Horror'%}">Horror</a></h3>
            </div>
            <div class="genre">
                <img src="{% static 'film_images/thriller.jpg' %}" alt="Thriller">
                <h3><a href="{% url 'ReviewFlix:Thriller'%}">Thriller</a></h3>
            </div>
            <div class="genre">
                <img src="{% static 'film_images/documentary.jpg' %}" alt="Documentary">
                <h3><a href="{% url 'ReviewFlix:Documentary'%}">Documentary</a></h3>
            </div>
            <div class="genre">
                <img src="{% static 'film_images/animated.jpg' %}" alt="Animated">
                <h3><a href="{% url 'ReviewFlix:Animated'%}">Animated</a></h3>
            </div>
            <!-- Add more genres as needed -->
        </div>
    </div>
{% endblock %}

templates/ReviewFlix/Home.html
{% extends 'ReviewFlix/base.html' %}
{% load staticfiles %}


{% block title_block %}
    HomePage
{% endblock %}

{% block additional_css %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/css/splide.min.css" rel="stylesheet">
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/js/splide.min.js"></script>
    <script src="{% static 'js/carousel.js' %}"></script>
{% endblock %}
  

{% block welcome_message %}
    <li style="white-space: nowrap;" id="welcome-message">Hey, {{ user.username }}!</li>
{% endblock %}
{% block body_block %}


    <div class="wrapper">
        <div class="description">
            <h1 class="about">About ReviewFlix</h1>
            <p class="paragraph">Introducing ReviewFlix, your ultimate destination for all things movies! Dive into a world of cinematic wonders where every film has its story told through insightful ratings and reviews. Whether you're seeking a thrilling adventure, a heartwarming romance, or a laugh-out-loud comedy, ReviewFlix has you covered. With our user-friendly interface and vibrant community of movie enthusiasts, discovering your next favorite flick has never been easier. Join us today and unlock the magic of cinema with ReviewFlix!</p>
            
        </div>
        

        <div class="screen_logo">
            <img class="screen_img" src="{% static 'film_images/screen_logo.png' %}"/>
        </div>

    </div>

    
    {% if top_films %}
    <section id="image-carousel" class="splide" aria-label="Beautiful Images">
        <div class="splide__track">
                <ul class="splide__list">
                {% for film in top_films %}
                    <li class="splide__slide">
                        <div class="title_button">
                            <h1 class="title">Top 5 Highest Rated Films:</h1>
                            <h2 class="movie_title">{{ film.Title }}</h2>
                            <h3 class="ranking">Average Rating: {{ film.avg_rating|floatformat:1}}</h3>
                            <a href="{% url 'ReviewFlix:Film' film.id %}" class="button">More Details</a>
                        </div>
                        {% if film.image %}
                            <img class="img_slide_bg" src="{{ film.image.url }}" alt="{{ film.Title }}"/>
                        {% else %}
                            <p>No image available.</p>
                        {% endif %}
                        
                    </li>

                {% endfor %}  
                </ul>

               
        </div>
    </section>
    {% endif %}




    <div class="review_section">
        <div class="title_review">
            <h1>Recommended films</h1>
        </div>

         
        <div class="grid">
            
            <div class="img_review">
                <img class="img_slide" src="{% static 'film_images/pulp_fiction.jpeg' %}"/>
                <a href="{% url 'ReviewFlix:Film' pulp_fiction.id  %}review" class="button btn_reviews">Write review</a>

            </div>

            <div class="img_review">
                <img class="img_slide" src="{% static 'film_images/get_out.jpg' %}"/>
                <a href="{% url 'ReviewFlix:Film' getOut.id %}review" class="button btn_reviews">Write review</a>

            </div>

            <div class="img_review">
                <img class="img_slide" src="{% static 'film_images/shawshank.jpg' %}"/>
                <a href="{% url 'ReviewFlix:Film' shawshank.id %}review" class="button btn_reviews">Write review</a>

            </div>
        </div>
    </div>



   

{% endblock %}

templates/ReviewFlix/Horror.html
{% extends 'ReviewFlix/base.html' %}
{% load staticfiles %}


{% block title_block %}
    Horror
{% endblock %}

{% block additional_css %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/css/splide.min.css" rel="stylesheet">
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/js/splide.min.js"></script>
    <script src="{% static 'js/carousel.js' %}"></script>
{% endblock %}

{% block body_block %}
    <h1 style="text-align: center;">Welcome to the Horror Movies Page</h1>
    <section id="image-carousel" class="splide" aria-label="Beautiful Images">
        <div class="splide__track">
                <ul class="splide__list">
                {% for film in films %}
                    <li class="splide__slide">
                        <div class="title_button">
                            <h2 class="movie_title">{{ film.Title }}</h2>
                            <a href="{% url 'ReviewFlix:Film' film.id %}" class="button">More Details</a>
                        </div>
                        {% if film.image %}
                            <img class="img_slide_bg" src="{{ film.image.url }}" alt="{{ film.Title }}"/>
                        {% else %}
                            <p>No image available.</p>
                        {% endif %}
                        
                    </li>

                {% endfor %}  
                </ul>

               
        </div>
    </section>
{% endblock %}

templates/ReviewFlix/Register.html
{% extends 'ReviewFlix/base.html' %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    <div style="background-color: white; width: 50%; margin: 0 auto; padding: 20px; border: 1px solid #ccc; border-radius: 5px;">
        <h1 style="text-align: center;">Register for ReviewFlix</h1>
        {% if registered %}
            <strong style="text-align: center; display: block;">Thank you for registering!</strong>
            <div style="text-align: center;">
                <a href="{% url 'ReviewFlix:Home' %}" style="color: blue;">Return to the homepage.</a><br />
            </div>
        {% else %}
            <strong style="text-align: center; display: block;">Register here!</strong><br />
            <form id="user_form" method="post" action="{% url 'ReviewFlix:Register' %}" enctype="multipart/form-data" style="text-align: center;">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <br />
                <input type="submit" name="submit" value="Register" style="background-color: #007bff; color: white; border: none; padding: 10px 20px; cursor: pointer;">
            </form>
        {% endif %}
    </div>
{% endblock %}

templates/ReviewFlix/Watchlist.html
{% extends 'ReviewFlix/base.html' %}
{% load staticfiles %}


{% block title_block %}
    Watchlist
{% endblock %}

{% block additional_css %}
    <link rel="stylesheet" href="{% static 'css/watchlist.css' %}">
    <link rel="stylesheet" href="{% static 'css/film.css' %}">
{% endblock %}


{% block body_block %}
    <div class="container">

        <h1 class="title">Welcome to the Watchlist Page</h1>

        <div class="wrapper">
            {% if watchlist_entries %}
            <ul>
                {% for entry in watchlist_entries %}
                    <li>

                        {% if entry.Film.image %}
                            <img class="img_slide_bg" src="{{ entry.Film.image.url }}" alt="{{ entry.Film.Title }}"/>
                        {% else %}
                            <p>No image available.</p>
                        {% endif %}
                        <div class="text_wrapper">
                            <a href="{% url 'ReviewFlix:Film' film_id=entry.Film.id %}">{{ entry.Film.Title }}</a>
                            <p><strong>Genre:</strong> {{ entry.Film.Genre }}</p>
                            <p><strong>Description:</strong> {{ entry.Film.Description }}</p>

                            <form method="post" action="{% url 'ReviewFlix:remove_from_watchlist' %}">
                                {% csrf_token %}
                                <input class="btn" type="hidden" name="film_id" value="{{ entry.Film.id }}">
                                <input class="btn" type="submit" value="Remove from Watchlist">
                            </form>
                        </div>
                    </li>
                {% empty %}
                    <p>No movies in your watchlist.</p>
                {% endfor %}
            </ul>
            {% endif %}

        </div>

    </div>
{% endblock %}

templates/ReviewFlix/base.html
<!DOCTYPE html>
{% load static %}

<html>
  <head>
    <title>
      ReviewFlix - 
      {% block title_block %}
        Base Page
      {% endblock %}
    </title>
    <link rel = "stylesheet", href = "{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">

    {% block additional_css %}{% endblock %}
    


   

 
  </head>


  <body>
    <header>

        

        <ul>
          <div class="wrapper_links">
            <img class="logo_img" src="{% static 'film_images/logo.png' %}"/>
            <li><a href="{% url 'ReviewFlix:Home' %}">Homepage</a></li>
            <li class="dropdown">
              <a href="{% url 'ReviewFlix:Genres' %}">Genres</a>
              <div class="dropdown-content">
                <ul class="dropdown_list">
                  <li><a href="{% url 'ReviewFlix:Drama'%}">Drama</a></li>
                  <li><a href="{% url 'ReviewFlix:Comedy'%}">Comedy</a></li>
                  <li><a href="{% url 'ReviewFlix:Horror'%}">Horror</a></li>
                  <li><a href="{% url 'ReviewFlix:Thriller'%}">Thriller</a></li>
                  <li><a href="{% url 'ReviewFlix:Documentary'%}">Documentary</a></li>
                  <li><a href="{% url 'ReviewFlix:Animated'%}">Animated</a></li>
                </ul>
              </div>
            </li>
            {% if user.is_authenticated %}
              <li><a href="{% url 'ReviewFlix:Watchlist' %}">Watchlist</a></li>
          </div>
          <div class="logout_wrapper">
              {% block welcome_message %}{% endblock %}
              <li><a id="authorised_lst" href="{% url 'ReviewFlix:Logout' %}">Logout</a></li>
              {% else %}
              <div class ="authorised_lst">
                <li><a href="{% url 'ReviewFlix:Register' %}">Register</a></li>
                <li><a href="{% url 'ReviewFlix:Login' %}">Login</a></li>
              </div>
          </div>
          
          
            
          {% endif %}
        </ul>
        

      
    </header>
  
   <div class="about_block">
      <div class="container">
        
        {% block body_block %}        
        {% endblock %}
      </div>
    </div>

    <div class="btn_up">
      <button onclick="topFunction()" id="myBtn" title="Go to top">&#x2191;</button>
    </div>

   
    <footer>
      <ul class="footer_menu">

        <div class="main_menu">
          {% if user.is_authenticated %}
          {% if user.userprofile.isProducer%}
          <li><a href="{% url 'ReviewFlix:AddAMovie' %}">Add a Movie</a></li>
          {% endif %}
          {% endif %}
          <li><a href="{% url 'ReviewFlix:FAQ' %}">FAQs</a></li>
        </div>
        
        
      </ul>
    </footer>

     {% block javascript %}
    <script src= "{% static 'js/script.js' %}"></script>
    {% endblock %}
  </body>
</html>